services:
  - docker

branches:
  only:
    - master

os:
  - linux

env:
  global:
    - DATE=`TZ=America/New_York date "+%Y-%m-%d-%H%M"`
    - DOCKER_IMAGE="leanda/chemical-file-parser"
    - DOCKER_TESTS_IMAGE="leanda/chemical-parser-tests"

script:
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  # - cd tests/Sds.ChemicalFileParser.Tests && docker build -t $DOCKER_TESTS_IMAGE:latest .
  # - yes | cp -rf Sds.ChemicalFileParser.Tests/.env.travis-ci Sds.ChemicalFileParser.Tests/.env
  # - cd Sds.ChemicalFileParser.Tests && docker-compose up --abort-on-container-exit

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE # Pushes both date and latest