version: '3'

services:
    chemical-file-parser-service:
        container_name: chemical-file-parser-service
        image: leanda/chemical-file-parser:latest
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        volumes:
        - ${OSDR_TEMP_FILES_FOLDER}:/temps/
        - ${OSDR_LOG_FOLDER}:/logs/
        build:
            context: .
        ports:
        - 8982:8081
        networks:
        - osdr-net-ext
            
networks:
    osdr-net-ext:
        external:
            name: osdr-sys-net
